openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/tengroup/tenplatform-api/1.0.0
info:
  description: A spec for the Ten Platform API.
  version: "1.0.0"
  title: Ten Platform API
  contact:
    email: someone@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /plans:
    get:
      description: Returns an array of all membership plans
      responses: 
        '200':
          description: A JSON array of membership plans
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MembershipPlan'
                  
  /plans/{id}:
    get:
      description: Returns a single membership plan, by id
      parameters:
        - name: id
          in: path
          description: id of plan to fetch
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single membership plan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MembershipPlan'

components:
  schemas:
    MembershipPlan:
      required:
        - id
        - name
        - description
        - annualMembershipPrice
        - monthlyMembershipPrice
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        annualMembershipPrice:
          allOf: 
            - $ref: '#/components/schemas/Price'
        monthlyMembershipPrice:
          allOf:
            - $ref: '#/components/schemas/Price'
        promoCode:
          type: string
        totalCost:
          allOf:
            - $ref: '#/components/schemas/Price'
            
    Price:
      required:
        - amount
        - currencyCode
      properties:
        amount:
          type: number
        currencyCode:
          type: string