openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/tengroup/tenplatform-api/1.0.0
info:
  description: A spec for the Ten Platform API.
  version: "1.0.0"
  title: Ten Platform API
  contact:
    email: someone@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /plans:
    get:
      description: Returns an array of all membership plans
      responses: 
        '200':
          description: A JSON array of membership plans
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MembershipPlan'
  /plans/{id}:
    get:
      description: Returns a single membership plan, by id
      parameters:
        - name: id
          in: path
          description: id of plan to fetch
          required: true
          schema:
            type: number
        - name: frequency
          in: query
          description: payment frequency(i.e monthly or yearly)
          required: true
          schema:
            type: string
        - name: promoCode
          in: query
          description: a promo code to apply to a membership plan
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A single membership plan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MembershipPlan'
  /restaurants:
    get:
      tags:
        - restaurants
      description: Returns all restaurants
      responses:
        '200':
          description: A list of restaurants.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
  /restaurants/{id}:
    get:
      tags:
        - restaurants
      description: Returns restaurants based on ID
      summary: Find restaurants by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: restaurant response
          content:
            '*/*' :
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
components:
  schemas:
    MembershipPlan:
      required:
        - id
        - name
        - description
        - annualMembershipPrice
        - monthlyMembershipPrice
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        annualMembershipPrice:
          allOf: 
            - $ref: '#/components/schemas/Price'
        monthlyMembershipPrice:
          allOf:
            - $ref: '#/components/schemas/Price'
        promoCode:
          type: string
        totalCost:
          allOf:
            - $ref: '#/components/schemas/Price'
    Price:
      required:
        - amount
        - currencyCode
      properties:
        amount:
          type: number
        currencyCode:
          type: string
    Restaurant:
      type: object
      required:
      - name
      - id
      properties:
        id:
          type: integer
          example: 0
        name:
          type: string
          example: 'Sushi Samba'
        description:
          type: string
          example: 'The best sushi around'
        images:
          type: array
          items:
            $ref: '#/components/schemas/Image'
    
    Image:
      type: object
      properties:
        url:
          type: string
          description: 'Absolute URL for the image'
          example: 'https://imgur.com/gallery/u1SZp'